Web/Controllers/PensionFundController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Auctus.Service;
using Microsoft.Extensions.Logging;
using Auctus.Web.Model.Home;
using System.Net;
using Microsoft.Extensions.Caching.Memory;
using Auctus.Model;
using Auctus.Util;
using Microsoft.AspNetCore.SignalR.Infrastructure;
using Auctus.Web.Hubs;
using Auctus.DomainObjects.Contracts;
using Newtonsoft.Json.Serialization;
using Newtonsoft.Json;
using System.Collections.Concurrent;

namespace Web.Controllers
{
    public class PensionFundController : BaseController
    {
        private static readonly ConcurrentDictionary<string, string> CONTRACT_TRANSACTING = new ConcurrentDictionary<string, string>();

        public PensionFundController(ILoggerFactory loggerFactory, Cache cache, IServiceProvider serviceProvider) : base(loggerFactory, cache, serviceProvider) { }

        [Route("/PensionFund/{contractAddress}")]
        public IActionResult Index(string contractAddress)
        {
            return View(PensionFundsServices.GetPensionFundInfo(contractAddress));
        }

        [HttpGet]
        [Route("/PensionFund/GetWithdrawalInfo")]
        public IActionResult GetWithdrawalInfo(string contractAddress)
        {
            return Json(PensionFundsServices.GetWithdrawalInfo(contractAddress));
        }

        [HttpPost]
        [Route("/PensionFund/GeneratePayment")]
        public IActionResult GeneratePayment(string contractAddress, int monthsAmount)
        {
            if (CanTransactWith(contractAddress))
            {
                try
                {
                    return Json(PensionFundsServices.GeneratePayment(contractAddress, monthsAmount));
                }
                finally
                {
                    ReleaseTransactionWith(contractAddress);
                }
            }
            else
                return new EmptyResult();
        }

        [HttpPost]
        [Route("/PensionFund/ReadPayments")]
        public IActionResult ReadPayments(string contractAddress)
        {
            try
            {
                if (CanTransactWith(contractAddress))
                {
                    try
                    {
                        Progress progress = PensionFundsServices.ReadPayments(contractAddress);
                        return Json(new { success = progress.Completed, currentProgress = Json(progress).Value });
                    }
                    finally
                    {
                        ReleaseTransactionWith(contractAddress);
                    }
                }
            }
            catch (Exception ex)
            {
                Logger.LogError(new EventId(2), ex, string.Format("Erro on ReadPayments {0}.", contractAddress));
            }
            return Json(new { success = false });
        }

        [HttpPost]
        [Route("/PensionFund/GenerateWithdrawal")]
        public IActionResult GenerateWithdrawal(string contractAddress)
        {
            if (CanTransactWith(contractAddress))
            {
                try
                {
                    return Json(PensionFundsServices.GenerateWithdrawal(contractAddress),
                        new JsonSerializerSettings { ContractResolver = new DefaultContractResolver() });
                }
                finally
                {
                    ReleaseTransactionWith(contractAddress);
                }
            }
            else
                return new EmptyResult();
        }

        [HttpPost]
        [Route("/PensionFund/ReadWithdrawal")]
        public IActionResult ReadWithdrawal(string contractAddress)
        {
            try
            {
                Withdrawal withdrawal = PensionFundsServices.ReadWithdrawal(contractAddress);
                return Json(new { success = (withdrawal == null || withdrawal.Completed), data = Json(withdrawal).Value });
            }
            catch (Exception ex)
            {
                Logger.LogError(new EventId(3), ex, string.Format("Erro on ReadWithdrawal {0}.", contractAddress));
            }
            return Json(new { success = false });
        }

        private bool CanTransactWith(string contractAddress)
        {
            return CONTRACT_TRANSACTING.TryAdd(contractAddress, null);
        }

        private void ReleaseTransactionWith(string contractAddress)
        {
            CONTRACT_TRANSACTING.TryRemove(contractAddress, out string nullValue);
        }
    }
}

Web/Views/PensionFund/Index.cshtml
@using Auctus.Model
@model PensionFundInfo

@Html.Partial("_Header", Model?.ContractAddress)
@Html.Partial("_Timeline", 0)
@Html.Partial("_FundSummary", Model?.PensionFundName.ToUpper())
@Html.Partial("_Charts")

@Html.Partial("_TransactionHistory")

@Html.Partial("_Withdraw")
@Html.Partial("_WithdrawCompleted")
@Html.Partial("_Payment")

@section style{
    <link rel=stylesheet href="~/css/dashboard.css">
    <link href="~/lib/c3/c3.min.css" rel="stylesheet">
    <link rel=stylesheet href="~/lib/noUiSlider/nouislider.min.css">
}

@section scripts{
    <script type="text/javascript">
        var urlGenerateWithdraw = '@Url.Action("GenerateWithdrawal", "PensionFund")';
        var urlGeneratePayment = '@Url.Action("GeneratePayment", "PensionFund")';
        var urlGetPaymentInfo = '@Url.Action("GetWithdrawalInfo", "PensionFund")';
        var urlReadPayment = '@Url.Action("ReadPayments", "PensionFund")';
        var urlReadWithdraw = '@Url.Action("ReadWithdrawal", "PensionFund")';
        var urlGetPayments = '@Url.Action("Payments", "PensionFund")';
        var urlGetWithdraw = '@Url.Action("Withdrawal", "PensionFund")';
        var pensionFundData = JSON.parse('@Html.Raw(Json.Serialize(Model))');
    </script>
    <script src="~/lib/d3/d3.min.js" charset="utf-8"></script>
    <script src="~/lib/c3/c3.min.js"></script>
    <script type="text/javascript" src="~/js/dashboard/main.js"></script>
    <script type="text/javascript" src="~/js/dashboard/charts.js"></script>
    <script type="text/javascript" src="~/lib/noUiSlider/nouislider.min.js"></script>
}   

Web/Views/PensionFund/_Charts.cshtml
<div class="fund-summary container">
    <div class="row">
        <div class="col-lg-7">
            <div class="card chart values-chart">
                <div class="title">
					<img src="../images/dashboard/trending-up.png" />
				    <span>VALUES CHART</span>
				</div>
                <div>
                    <div id="valuesChart"></div>
                    <span id="noDataValuesChart" style="display: none;">No data to display chart</span>
                </div>
            </div>
        </div>
		<div class="col-lg-5">
            <div class="card chart">
                <div class="title">
					<img src="../images/dashboard/assets-icon.png" />
				    <span>ASSETS</span>
				</div>
                <div class="row">
                    <div class="col-md-12 text-center">
                        <div class="btn-group" data-toggle="buttons">
                            <span class="btn active">
                                <input type="radio" name="chart-options" id="allocation" autocomplete="off" checked> ALLOCATION
                            </span>
                            <span class="btn">
                                <input type="radio" name="chart-options" id="variation" autocomplete="off"> RETURN
                            </span>
                        </div>
                    </div>
                </div>
				<div class="row">
					<div id="allocation-chart"></div>
                    <div id="variation-chart" style="display: none;"></div>
				</div>
            </div>
        </div>
    </div>
</div>

Web/Views/PensionFund/_FundSummary.cshtml
@model string
<div class="fund-summary container">
    <div class="row">
		<div class="col-xs-12">
			<div class="card">
				<div class="title">
					<img src="../images/dashboard/bar-chart-2.png" />
				    <span>@Model</span>
				</div>
                <div class="sumary-info row">
                    <div class="col-lg-2">
                        <span class="money" id="totalInvested">-</span>
                        <div class="label">TOTAL INVESTED</div>
                    </div>
                    <div class="col-lg-2">
                        <span class="money" id="totalVested">-</span>
                        <div class="label">TOTAL VESTED</div>
                    </div>
                    <div class="col-lg-2">
                        <span id="totalToken">-</span>
                        <div class="label">TOTAL TOKEN</div>
                    </div>
                    <div class="col-lg-2">
                        <div id="nextVestingDate"><span>-</span></div>
                        <div class="label">NEXT VESTING DATE</div>
                    </div>
                    <div class="col-lg-2">
                        <span class="money" id="feePaid">-</span>
                        <div class="label">FEE PAID (FUND)</div>
                    </div>
                    <div class="col-lg-2">
                        <span class="money" id="auctusFee">-</span>
                        <div class="label">FEE PAID (AUCTUS)</div>
                    </div>
                </div>
			</div>
		</div>
    </div>
</div>

Web/Views/PensionFund/_Header.cshtml
@model string
@{
    //string tooltipContentShare = string.Format("<br/><div>This is the result of your investment. If you wish, you can start over e test another assets composition or fund characteristics to see how you perform!</div><br /><div>We are very excited about our project and we hope nao you are too! You can support it in the following link:</div><div><a target='_blank' href='https://demo.auctus.org/PensionFund/{0}'>demo.auctus.com/PensionFund/{0}</a></div><br /><div class='popup-share-footer-text'><span>SHARE YOUR SIMULATION</span></div><br /><div class='dashboard-container'><div class='popup-share-btn popup-share-btn-left'><img src='/images/twitter.png' height='40' width='40' /></div><div class='popup-share-btn popup-share-btn-center'><img src='/images/facebook.png' height='40' width='40' /></div><div class='popup-share-btn popup-share-btn-right'><img src='/images/linkedin.png' height='40' width='40' /></div></div>", Model);
    string tooltipContentShare = string.Format("<br/><div>This is the result of your investment. If you wish, you can start over and test another assets composition or fund characteristics to see how you perform!</div><br /><div>We are very excited about our project and we hope now you are too! You can support it in the following link:</div><div><a target='_blank' href='https://demo.auctus.org/PensionFund/{0}'>demo.auctus.com/PensionFund/{0}</a></div><br /><div class='popup-share-footer-text'><span>SHARE YOUR SIMULATION</span></div><br /><div class='dashboard-container popup-share-footer-copy'><div class='popup-share-copy'><span class='popup-share-copy-text'>COPY URL</span></div></div>", Model);
}
<div class="dashboard-container dashboard-container-full header-dashboard">
    <div class="auctus-logo auctus-logo-margin"><a target="_blank" href="https://auctus.org"><img src="~/images/logo.png" height="40" /></a></div>
    <div class="header-icon plus-circle plus-circle-width"><a target="_blank" href="https://demo.auctus.org/Register"><img src="~/images/plus-circle.png" height="20" /></a></div>
    <div class="header-text new-simulation"><span onclick="window.open('https://demo.auctus.org/Register');">NEW SIMULATION</span></div>
    <div class="header-icon header-share share-symbol"
        data-toggle="popover" 
        data-trigger="click"
        data-placement="bottom"
        title=""
        data-content="@tooltipContentShare"
        data-html="true"><img src="~/images/share.png" height="20" /></div>
    <div class="header-text header-share share"
        data-toggle="popover" 
        data-trigger="click"
        data-placement="bottom"
        title=""
        data-content="@tooltipContentShare"
        data-html="true"><span>SHARE</span></div>
</div>

Web/Views/PensionFund/_Payment.cshtml
<div class="modal fade" id="paymentModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-title-center modal-header">
                <h4 class="modal-title"><span>SIMULATE CONTRIBUTIONS</span></h4>
            </div>
            <div class="modal-body">
                <div class="dashboard-container dashboard-container-full">
                    <div class="modal-slider modal-slider-text">NUMBER OF MONTHS</div>
                    <div class="modal-slider" id="slider"></div>
                    <div class="modal-month form-group bmd-form-group">
                        <input type="number" id="month" min="1" max="60" step="1" />
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">Cancel</span></button>
                <button type="button" class="btn btn-primary" onclick="Dashboard.payment();"><span>Confirm</span></button>
            </div>
        </div>
    </div>
</div>

Web/Views/PensionFund/_Timeline.cshtml
@model int

<div class="dashboard-container dashboard-container-full timeline-container">
    <div class="loading-container" hidden="hidden" >
        <div class="progress">
            <div class="indeterminate"></div>
        </div>
    </div>
    <div class="timeline-space"></div>
    <div class="dashboard-container timeline-grid"
         data-toggle="popover"
         data-trigger="click"
         data-placement="bottom"
         title="THIS IS YOUR TIMELINE"
         data-content="<div>Here you can simulate how your fund will perform for a period of up to 5 years. We'll be using the historical performance of the assets to simulate the results.</div><br/><div class='dashboard-container'><div class='transaction-btn btn-payment popup-timeline-btn'><img src='/images/payment.png' class='transaction-btn-img' height='25' width='30' /></div><div class='popup-timeline-btn-text'>Press this button to <b>simulate a payment</b> for a desired period of time.</div></div><br/><div class='dashboard-container'><div class='transaction-btn btn-withdrawal popup-timeline-btn'><img src='/images/withdrawal.png' class='transaction-btn-img' height='25' width='37' /></div><div class='popup-timeline-btn-text'>Press this button when you are ready to <b>withdraw</b> your investiment.</div></div><br/><div class='popup-timeline-footer'><span>LET'S DO THIS!</span></div>"
         data-html="true">
        @for (int line = 1; line <= 60; ++line)
        {
            string externalVerticalLine = "";
            string internalVerticalLine = "";
            string horizontalLine = "";
            if (line % 12 == 0)
            {
                // if (line != 60)
                // {
                externalVerticalLine += "timeline-grid-vertical-line timeline-grid-vertical-line-big";
                // }
                internalVerticalLine = "timeline-grid-height-half";
                horizontalLine += " timeline-grid-height-half";
            }
            else
            {
                internalVerticalLine = "timeline-grid-height-tiny timeline-grid-vertical-line timeline-grid-vertical-line-tiny";
                horizontalLine += " timeline-grid-height-tiny";
            }
            horizontalLine += line <= Model ? " timeline-grid-horizontal-line-complete" : " timeline-grid-horizontal-line-pending";

            <div class="timeline-grid-height-full timeline-grid-width-fraction">
                <div class="timeline-grid-width-full timeline-grid-height-half @externalVerticalLine">
                    <div class="@internalVerticalLine">
                        <div data-line="@line" class="timeline-grid-width-full timeline-grid-horizontal-line @horizontalLine"></div>
                    </div>
                </div>
                @if (line % 12 == 0)
                {
                    <div class="timeline-grid-height-half timeline-grid-width-fraction">
                        <div class="timeline-text"><span class="timeline-text-year">@string.Format("YEAR {0}", line / 12)</span></div>
                    </div>
                }
            </div>
        }
    </div>
    <div class="dashboard-container timeline-buttons">
        <div title="Simulate Contributions" id="paymentBtn" class="transaction-btn btn-payment timeline-btn-payment">
            <img src="~/images/payment.png" class="transaction-btn-img" height="25" width="30" />
        </div>
        <div title="Withdraw" id="withdrawBtn" class="transaction-btn btn-withdrawal timeline-btn-withdrawal">
            <img src="~/images/withdrawal.png" class="transaction-btn-img" height="25" width="37" />
        </div>
    </div>
</div>

Web/Views/PensionFund/_TransactionHistory.cshtml
<div class="fund-summary container">
    <div class="row">
        <div class="col-xs-12">
            <div class="card history-card">
                <div class="title">
                    <img src="../images/dashboard/clock.png" />
                    <span>TRANSACTION HISTORY</span>
                </div>
                <div class="history-table">
                    <div class="row table-header">
                        <div class="col-3">
                            <span>TRANSACTION DATE</span>
                        </div>
                        <div class="col-3">
                            <span>EMPLOYEE TOKEN PURCHASED</span>
                        </div>
                        <div class="col-3">
                            <span>EMPLOYER TOKEN PURCHASED</span>
                        </div>
                        <div class="col-3">
                            <span>STATUS</span>
                        </div>
                    </div>
                    <div class="table-content" style="display:none">
                        <div class="row row-template">
                            <div class="col-3">
                                <span>{TRANSACTION_DATE}</span>
                            </div>
                            <div class="col-3">
                                <span style="width: 70px; display: inline-block;">{EMPLOYEE_TOKEN}</span> <a class="{EMPLOYEE_TRANSACTION_LINK_CLASS}" href="{EMPLOYEE_TRANSACTION_LINK}" target="_blank"><span class="view-tx">View Tx</span></a>
                            </div>
                            <div class="col-3">
                                <span style="width: 70px; display: inline-block;">{EMPLOYER_TOKEN}</span> <a class="{EMPLOYER_TRANSACTION_LINK_CLASS}" href="{EMPLOYER_TRANSACTION_LINK}" target="_blank"><span class="view-tx">View Tx</span></a>
                            </div>
                            <div class="col-3 {TRANSACTION_STATUS_CLASS}">
                                <div class="bullet"></div><span>{TRANSACTION_STATUS}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Web/Views/PensionFund/_Withdraw.cshtml
<div class="modal fade" id="withdrawModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-title-center modal-header">
                <h4 class="modal-title"><span>WITHDRAW</span></h4>
            </div>
            <div class="modal-body">
                <div class="dashboard-container dashboard-container-full">
                    <div class="modal-withdraw-container">
                        <div class="modal-withdraw-internal"><img src="~/images/user-plus.png" height="20" width="22" /></div>
                        <div class="modal-withdraw-internal modal-money"><span class="employee-receivable">-</span></div>
                        <div class="modal-withdraw-internal modal-money-label">EMPLOYEE RECEIVABLE</div>
                    </div>
                    <div class="modal-withdraw-container">
                        <div class="modal-withdraw-internal"><img src="~/images/briefcase.png" height="20" width="22" /></div>
                        <div class="modal-withdraw-internal modal-money"><span class="company-receivable">-</span></div>
                        <div class="modal-withdraw-internal modal-money-label">COMPANY RECEIVABLE</div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">Cancel</span></button>
                <button type="button" class="btn btn-primary" onclick="Dashboard.withdraw();"><span>Confirm</span></button>
            </div>
        </div>
    </div>
</div>

Web/Views/PensionFund/_WithdrawCompleted.cshtml
<div class="modal fade" id="withdrawCompletedModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="close-modal">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-title-center modal-header">
                <h4 class="modal-title"><span>WITHDRAW COMPLETED!</span></h4>
            </div>
            <div class="modal-title-center"><a id="withdrawTransactionLink" href="./" target="_blank"><span class="view-tx">View Transaction</span></a></div>
            <div class="modal-body">
                <div class="dashboard-container dashboard-container-full">
                    <div class="modal-withdraw-container">
                        <div class="modal-withdraw-internal"><img src="~/images/user-plus.png" height="20" width="22" /></div>
                        <div class="modal-withdraw-internal modal-money"><span class="employee-receivable">-</span></div>
                        <div><a id="employeeWalletLink" href="./" target="_blank"><span class="view-tx">View Wallet</span></a></div>
                    </div>
                    <div class="modal-withdraw-container">
                        <div class="modal-withdraw-internal"><img src="~/images/briefcase.png" height="20" width="22" /></div>
                        <div class="modal-withdraw-internal modal-money"><span class="company-receivable">-</span></div>
                        <div><a id="employerWalletLink" href="./" target="_blank"><span class="view-tx">View Wallet</span></a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>