Web/Controllers/AssetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Caching.Memory;
using Auctus.Util;
using Microsoft.AspNetCore.SignalR.Infrastructure;
using Auctus.DomainObjects.Contracts;

namespace Web.Controllers
{
    public class AssetController : BaseController
    {
        public AssetController(ILoggerFactory loggerFactory, Cache cache, IServiceProvider serviceProvider) : base (loggerFactory, cache, serviceProvider) { }

        [HttpGet]
        public IActionResult GetGoldReference()
        {
            return GetJsonFromReferenceContract(ContractsServices.GetGoldReference());
        }

        [HttpGet]
        public IActionResult GetMSCIWorldReference()
        {
            return GetJsonFromReferenceContract(ContractsServices.GetMSCIWorldReference());
        }

        [HttpGet]
        public IActionResult GetSP500Reference()
        {
            return GetJsonFromReferenceContract(ContractsServices.GetSP500Reference());
        }

        [HttpGet]
        public IActionResult GetVWEHXReference()
        {
            return GetJsonFromReferenceContract(ContractsServices.GetVWEHXReference());
        }

        [HttpGet]
        public IActionResult GetBitcoinReference()
        {
            return GetJsonFromReferenceContract(ContractsServices.GetBitcoinReference());
        }

        private JsonResult GetJsonFromReferenceContract(ReferenceContract referenceContract)
        {
            return Json(new { Address = referenceContract.Address, Name = referenceContract.Description,
                Values = referenceContract.ReferenceValue.Select(c => new double[]{ c.Period, c.Value}) });
        }
    }
}

Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Auctus.Service;
using Microsoft.Extensions.Logging;
using Auctus.Web.Model.Home;
using System.Net;
using Microsoft.Extensions.Caching.Memory;
using Auctus.Model;
using Auctus.Util;
using Microsoft.AspNetCore.SignalR.Infrastructure;
using Auctus.Web.Hubs;
using Auctus.DomainObjects.Contracts;

namespace Web.Controllers
{
    public class HomeController : BaseController
    {
        public HomeController(ILoggerFactory loggerFactory, Cache cache, IServiceProvider serviceProvider) : base(loggerFactory, cache, serviceProvider) { }
        
        public IActionResult Index()
        {
            return View();
        }

        [Route("/Register")]
        public IActionResult StartDemo()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Save(Wizard model)
        {
            try
            {
                if (model == null)
                    throw new ArgumentException("Invalid data.");
                if (!IsValidRecaptcha(model.Captcha))
                    throw new InvalidOperationException("Invalid captcha.");

                int pensionFundId = PensionFundsServices.CreateUnprocessedEntry(model.Fund, model.Company, model.Employee);
                return Json(new { PensionFundId = pensionFundId }); 
            }
            catch(Exception e)
            {
                Response.StatusCode = 400;
                if (e is ArgumentException)
                    return Json(e.Message);
                return Json("We’re sorry, we had an unexpected error! Please try again in a minute.");
            }
        }
        
        //[HttpPost]
        //public IActionResult CheckPensionFundCreation(int pensionFundId)
        //{
        //    if (!string.IsNullOrEmpty(ConnectionId))
        //    {
        //        Task.Factory.StartNew(() =>
        //        {
        //            var hubContext = HubConnectionManager.GetHubContext<AuctusDemoHub>();
        //            try
        //            {
        //                var pensionFundCreated = PensionFundsServices.CheckPensionFundCreation(pensionFundId);
        //                if (pensionFundCreated != null)
        //                    hubContext.Clients.Client(ConnectionId).creationCompleted(Json(
        //                        new
        //                        {
        //                            SmartContractCode = pensionFundCreated.Item2,
        //                            TransactionHash = pensionFundCreated.Item1
        //                        }));
        //                else
        //                    hubContext.Clients.Client(ConnectionId).creationUncompleted(pensionFundId);
        //            }
        //            catch (Exception ex)
        //            {
        //                Logger.LogError(new EventId(1), ex, string.Format("Erro on CheckPensionFundCreation {0}.", pensionFundId));
        //                hubContext.Clients.Client(ConnectionId).creationUncompleted(pensionFundId);
        //            }
        //        });
        //        return Json(new { success = true });
        //    }
        //    else
        //        return Json(new { success = false });
        //}

        [HttpPost]
        public IActionResult CheckPensionFundCreation(int pensionFundId)
        {
            try
            {
                var pensionFundCreated = PensionFundsServices.CheckPensionFundCreation(pensionFundId);
                if (pensionFundCreated != null)
                    return Json(new { success = true, smartContractCode = pensionFundCreated.Item2, transactionHash = pensionFundCreated.Item1 });
            }
            catch (Exception ex)
            {
                Logger.LogError(new EventId(1), ex, string.Format("Erro on CheckPensionFundCreation {0}.", pensionFundId));
            }
            return Json(new { success = false });
        }

        [HttpPost]
        public IActionResult CheckContractMined(String transactionHash)
        {
            try
            {
                var pensionFundContract = PensionFundsServices.GetPensionFundContract(transactionHash);
                if (pensionFundContract == null)
                    throw new InvalidOperationException("Invalid transaction hash");

                if (pensionFundContract.BlockNumber.HasValue)
                    return Json(new { success = true, address = pensionFundContract.Address, blockNumber = pensionFundContract.BlockNumber, transactionHash = pensionFundContract.TransactionHash });
            }
            catch (Exception ex)
            {
                Logger.LogError(new EventId(1), ex, string.Format("Erro on CheckContractMined {0}.", transactionHash));
            }
            return Json(new { success = false });
        }

        //[HttpPost]
        //public IActionResult CheckContractMined(String transactionHash)
        //{
        //    if (!string.IsNullOrEmpty(ConnectionId))
        //    {
        //        Task.Factory.StartNew(() =>
        //        {
        //            var hubContext = HubConnectionManager.GetHubContext<AuctusDemoHub>();
        //            try
        //            {
        //                var pensionFundContract = PensionFundsServices.GetPensionFundContract(transactionHash);
        //                if (pensionFundContract == null)
        //                    throw new InvalidOperationException("Invalid transaction hash");

        //                if (pensionFundContract.BlockNumber.HasValue)
        //                    hubContext.Clients.Client(ConnectionId).deployCompleted(Json(
        //                        new
        //                        {
        //                            Address = pensionFundContract.Address,
        //                            BlockNumber = pensionFundContract.BlockNumber,
        //                            TransactionHash = pensionFundContract.TransactionHash
        //                        }));
        //                else
        //                    hubContext.Clients.Client(ConnectionId).deployUncompleted(pensionFundContract.TransactionHash);
        //            }
        //            catch (Exception ex)
        //            {
        //                Logger.LogError(new EventId(1), ex, string.Format("Erro on CheckContractMined {0}.", transactionHash));
        //                hubContext.Clients.Client(ConnectionId).deployError();
        //            }
        //        });
        //        return Json(new { success = true });
        //    }
        //    else
        //        return Json(new { success = false });
        //}
    }
}

Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Web/Views/Home/Index.cshtml
﻿<div style="text-align: center; margin-top:10px">
    <div id="graphdiv"></div>
</div>
<div class="container landing">
    <div class="row" style="text-align: center; margin-bottom: 60px;">
        <div class="col-md-12">
            <img src="~/images/logo.png" class="landing-logo">
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 wizard-container">
            <div class="row">
                <div class="step active" id="step0" data-step-id="0">
                    <div class="row">
                    </div>
                    <div class="row">
                        <div class="col-lg-4 left">
                            <div class="pig-container">
                                <img src="~/images/landing/img-pig.png" class="img-pig" />
                            </div>
                        </div>
                        <div class="col-lg-7 right">
                            <div class="welcome-container">
                                <span class="welcome">WELCOME</span>
                                <span class="get-to-know">GET TO KNOW OUR PRODUCT</span>
                            </div>
                            <div class="demo-description">
                                <p>This demo was created to illustrate how Auctus aims to utilize the Ethereum Network, by emulating retirement plan constraints (for example 401(k) plans) into Smart Contracts.</p>
                               @* <p>Auctus is creating a product that will revolutionize the retirement market by providing smart contract powered retirement plans. We intend to make the creation of employer-sponsored retirement plans really simple, allowing companies of any size and from anywhere in the world to offer this benefit for its employees.</p>*@
                                
                                @*<i>DISCLAIMER: this is a demo, certain assumptions and simplifications were made to make the demo more understandable. We are for example using historical data to simulate performance.</i></p>*@
                            </div>
                            <a href="@Url.Action("StartDemo", "Home")" tabindex="1">
                                <div class="buttons-control-div" >
                                    <div class="start-button">
                                        <span class="next-button-label" style="margin-left: 25px;">TRY OUR DEMO</span>
                                        @*<img src="~/images/landing/play.png" class="play-ico" />*@
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="landing-blue-rectangle"></div>
        <img src="~/images/landing/img-wave.png" class="img-landing-waves" />
        <img src="~/images/landing/img-dots.png" class="img-landing-dots" />
    </div>
</div>
@section style{
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/loading.css" />
    <link rel=stylesheet href="~/lib/codemirror/codemirror.css">
    <link rel=stylesheet href="~/lib/noUiSlider/nouislider.min.css">
}

@section scripts{
    <script src="~/lib/codemirror/codemirror.js"></script>
    <script src="~/lib/codemirror/mode/javascript.js"></script>
    <script type="text/javascript" src="~/js/home.js"></script>
    <script type="text/javascript" src="~/lib/noUiSlider/nouislider.min.js"></script>
    <script src="~/js/registerCompany.js" asp-append-version="true"></script>
    <script src="~/js/registerEmployee.js" asp-append-version="true"></script>
}

Web/Views/Home/StartDemo.cshtml
﻿<div style="text-align: center; margin-top:10px">
    <div id="graphdiv"></div>
</div>
<div class="container">
    <div class="row">
        <div class="col-lg-12 wizard-container" style="text-align: center;">
            <div class="row">
                <div class="step active" id="step1" data-step-id="1">
                    @Html.Partial("_Stepper", 1)
                    @Html.Partial("_RegisterCompany")
                    @Html.Partial("_Buttons", false)
                </div>
                <div class="container step" id="step2" data-step-id="2" style="display:none">
                    @Html.Partial("_Stepper", 2)
                    @Html.Partial("_RegisterEmployee")
                    @Html.Partial("_Buttons", true)
                </div>
                <div class="step" id="step3" data-step-id="3" style="display:none">
                    @Html.Partial("_ContractDeploy")
                    @Html.Partial("_Buttons", false)
                </div>           
            </div>
        </div>
    </div>
</div>
<div class="about-auctus">
    <label>Want to know more about our project?<br /><a href="https://auctus.org/">https://auctus.org/</a></label>
</div>
@section style{
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/fundRegister.css" />
    <link rel="stylesheet" href="~/css/companyRegister.css" />
    <link rel="stylesheet" href="~/css/contractDeploy.css" />
    <link rel="stylesheet" href="~/css/loading.css" />
    <link rel=stylesheet href="~/lib/codemirror/codemirror.css">
    <link rel=stylesheet href="~/lib/noUiSlider/nouislider.min.css">
}

@section scripts{
    <script type="text/javascript">
        var urlGetGoldReference = '@Url.Action("GetGoldReference", "Asset")';
        var urlGetSP500Reference = '@Url.Action("GetSP500Reference", "Asset")';
        var urlGetVWEHXReference = '@Url.Action("GetVWEHXReference", "Asset")';
        var urlGetMSCIWorldReference = '@Url.Action("GetMSCIWorldReference", "Asset")';
        var urlGetBitcoinReference = '@Url.Action("GetBitcoinReference", "Asset")';
        var urlSaveFund = '@Url.Action("Save", "Home")';
        var urlCheckCreation = '@Url.Action("CheckPensionFundCreation", "Home")';
        var urlCheckDeploy = '@Url.Action("CheckContractMined", "Home")';
    </script>
    <script src="~/lib/codemirror/codemirror.js"></script>
    <script src="~/lib/codemirror/mode/javascript.js"></script>
    <script type="text/javascript" src="~/js/home.js"></script>
    <script type="text/javascript" src="~/lib/noUiSlider/nouislider.min.js"></script>
    <script src="~/js/registerCompany.js" asp-append-version="true"></script>
    <script src="~/js/registerEmployee.js" asp-append-version="true"></script>
}

Web/Views/Home/_ContractDeploy.cshtml
<div class="contract-deploy-content text-center">
    <div id="contract-being-deployed">
        <div class="contract-deploy-title">YOUR CONTRACT IS BEING DEPLOYED</div>
        <div class="contract-deploy-subtitle">The mining could take some time. In the meantime, feel free to check the source code below!</div>
        <div><a class="contract-deploy-link contract-deploy-tx-id-link" target="_blank" href="">View Transaction <i class="fa fa-external-link" aria-hidden="true"></i></a></div>
    </div>
    <div id="contract-deployed" style="display:none">
        <div class="contract-deploy-title"><img src="~/images/deployContract/check-circle.png" />CONTRACT DEPLOYED</div>
        <div class="contract-deploy-subtitle">All good! Proceed to the next step to see your personal dashboard!</div>
        <div>
            <a class="contract-deploy-link contract-deploy-tx-id-link" target="_blank" href="">View Transaction <i class="fa fa-external-link" aria-hidden="true"></i></a>
            <a class="contract-deploy-link contract-deploy-contract-address-link" target="_blank" href="">View Contract <i class="fa fa-external-link" aria-hidden="true"></i></a>
        </div>
    </div>
</div>

<div id="contract-deploy-code-wrapper" class="form-group">
    <textarea id="contract-deploy-code"></textarea>
</div>

Web/Views/Home/_RegisterCompany.cshtml
<form id="registerCompany">
    <div class="col-md-12 company-register">
        <div class="col-md-6 left">
            <div class="row">
                <div class="col-lg-4">
                </div>
                <div class="col-lg-7">
                    <div class="form-group col-title">401K PLAN FOR YOUR COMPANY</div>
                    <div class="form-group bmd-form-group">
                        <label for="companyNameInput" class="bmd-label-static">COMPANY NAME</label>
                        <input type="text" class="form-control" id="companyNameInput" placeholder="My company">
                    </div>
                    <div class="form-group bmd-form-group">
                        <label for="employerMatchingInput" class="bmd-label-static">MATCH RATE</label>
                        <input type="number" min="0" max="10000" pattern="[0-9]" value="100" class="form-control onlyInteger" id="employerMatchingInput" placeholder="00%"
                               data-toggle="popover" 
                               data-trigger="focus"
                               data-placement="right"
                               title="MATCH RATE"
                               data-content="<div>The percentage of each dollar of employee contributions that is matched (e.g., 50 cents on the dollar or 50 percent).</div>"
                               data-html="true">
                    </div>
                    <div class="form-group bmd-form-group">
                        <label for="maxCounterpartInput" class="bmd-label-static">MATCH CEILING</label>
                        <input type="number" min="0" max="100" pattern="[0-9]" value="6" class="form-control onlyInteger" id="maxCounterpartInput" placeholder="00%"
                               data-toggle="popover" 
                               data-trigger="focus"
                               data-placement="right"
                               title="MATCH CEILING"
                               data-content="<div>The limit on the percentage of employee contributions that is matched (e.g., employee’s contribution is matched up to 4 percent of salary).</div>"
                               data-html="true">
                    </div>
                </div>
                <div class="col-lg-1">
                </div>
            </div>
        </div>
        <div class="col-md-6 right">
            <div class="row">
                <div class="col-lg-1">
                </div>
                <div class="col-lg-11">
                    <div class="form-group text-left"><span class="col-title no-padding col-xs-5">VESTING</span><a class="link" data-toggle="modal" href="#" data-target="#advancedOptions">Advanced options</a></div>
                    <div class="row form-group">
                        <div class="col-md-12">
                            <div class="img-container">
                                <img class="Vesting" src="~/images/companyRegister/vesting_icons/vesting-calendar.png" />
                                <span class="number less">&lt;1</span>
                            </div>
                            <span class="vesting-title">BEFORE 1 YEAR OF SERVICE</span>
                            <span class="vesting-period hidden">0.5</span>
                            <div class="input-percentage">
                                <a tabindex="0" class="" role="button" data-toggle="popover" data-trigger="focus" title="VESTING"
                                   data-content="<div>Under graduated vesting, there is partial vesting for each year of service. Here, we have suggested the most common values for this type of benefit. <br><br>You can click on <a class='link' data-toggle='modal' href='#' data-target='#advancedOptions'>Advanced options</a> to  customize these values.</div>"
                                   data-html="true">
                                    <input id="lessOneYear" class="input text-center vesting-percentage" type="number" pattern="[0-9]" min="0" max="100" disabled="disabled" value="0" />
                                    <span class="percentage">%</span>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-12">
                            <div class="img-container">
                                <img class="Vesting" src="~/images/companyRegister/vesting_icons/vesting-calendar.png" />
                                <span class="number">1</span>
                            </div>
                            <span class="vesting-title">AFTER 1 YEAR OF SERVICE</span>
                            <span class="vesting-period hidden">1</span>
                            <div class="input-percentage">
                                <input id="afterOneYear" class="input text-center vesting-percentage" type="number" pattern="[0-9]" min="0" max="100" disabled="disabled" value="20" />
                                <span class="percentage">%</span>
                            </div>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-12">
                            <div class="img-container">
                                <img class="Vesting" src="~/images/companyRegister/vesting_icons/vesting-calendar.png" />
                                <span class="number">2</span>
                            </div>
                            <span class="vesting-title">AFTER 2 YEARS OF SERVICE</span>
                            <span class="vesting-period hidden">2</span>
                            <div class="input-percentage">
                                <input id="afterTwoYears" class="input text-center vesting-percentage" type="number" pattern="[0-9]" min="0" max="100" disabled="disabled" value="40" />
                                <span class="percentage">%</span>
                            </div>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-12">
                            <div class="img-container">
                                <img class="Vesting" src="~/images/companyRegister/vesting_icons/vesting-calendar.png" />
                                <span class="number">3</span>
                            </div>
                            <span class="vesting-title">AFTER 3 YEARS OF SERVICE</span>
                            <span class="vesting-period hidden">3</span>
                            <div class="input-percentage">
                                <input id="afterThreeYears" class="input text-center vesting-percentage" type="number" pattern="[0-9]" min="0" max="100" disabled="disabled" value="60" />
                                <span class="percentage">%</span>
                            </div>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-12">
                            <div class="img-container">
                                <img class="Vesting" src="~/images/companyRegister/vesting_icons/vesting-calendar.png" />
                                <span class="number">4</span>
                            </div>
                            <span class="vesting-title">AFTER 4 YEARS OF SERVICE</span>
                            <span class="vesting-period hidden">4</span>
                            <div class="input-percentage">
                                <input id="afterFourYears" class="input text-center vesting-percentage" type="number" pattern="[0-9]" min="0" max="100" disabled="disabled" value="80" />
                                <span class="percentage">%</span>
                            </div>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-12">
                            <div class="img-container">
                                <img class="Vesting" src="~/images/companyRegister/vesting_icons/vesting-calendar.png" />
                                <span class="number">5</span>
                            </div>
                            <span class="vesting-title">AFTER 5 YEARS OF SERVICE</span>
                            <span class="vesting-period hidden">5</span>
                            <div class="input-percentage">
                                <input id="afterFiveYears" class="input text-center vesting-percentage" type="number" pattern="[0-9]" min="0" max="100" disabled="disabled" value="100" />
                                <span class="percentage">%</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<div class="modal fade" id="advancedOptions" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
		<h4 class="modal-title" id="myModalLabel">CUSTOMIZED VESTING</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <p>In the slider below, you can decide for the first 5 years of service what percentage should be vested in the employees salary-deferral contributions.</p>
        <div id="slider"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" onclick="registerCompanyForm.cancel()">Cancel</button>
        <button type="button" class="btn btn-primary" onclick="registerCompanyForm.confirm()">Confirm</button>
      </div>
    </div>
  </div>
</div>